export const PLATFORM_PERMISSIONS = {
  METRICS_READ: 'PLATFORM_METRICS_READ',
  TENANTS_READ: 'PLATFORM_TENANTS_READ',
  AUDIT_READ: 'PLATFORM_AUDIT_READ',
  TENANT_STATUS_WRITE: 'PLATFORM_TENANT_STATUS_WRITE',
  TENANT_LIMITS_WRITE: 'PLATFORM_TENANT_LIMITS_WRITE',
  OPERATORS_MANAGE: 'PLATFORM_OPERATORS_MANAGE',
} as const

export type PlatformPermission = (typeof PLATFORM_PERMISSIONS)[keyof typeof PLATFORM_PERMISSIONS]

export const PERMISSION_DENIED_CODE = 'PERMISSION_DENIED'
